### ISSUE TITLE
spin_op does not maintain order of terms as defined

### ISSUE THREAD

**Issue by poojarao8** [NVIDIA/cuda-quantum#821] opened 2023-10-25 04:58 UTC
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

If you define a spin_op with multiple terms, there is an internal ordering that it defaults to for those terms.  For hamiltonian evolution problems where a circuit is constructed from the defined spin_op, this can lead to a different circuit than intended.

### Steps to reproduce the bug

```
from cudaq import spin

h = spin.z(0)*spin.x(1)
h += spin.y(0)*spin.x(1)
h += spin.x(0)*spin.y(1)

h.dump()

for term in h:
  print(term) 
```

### Expected behavior

The order in which the terms are added to the hamiltonian should be preserved, with possibly additional options to sort the terms in some specific way, based on weights, lexicographically, etc.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 
- **Python version**: 
- **C++ compiler**: 
- **Operating system**:

**Comment by amccaskey** [comment] 2023-10-25 10:48
For performance, the data structure used under the hood of spin_op is an unordered_map. The docs for the class mention that you should therefore not depend on ordering of the terms. If you need to retain ordering of the terms you should construct your own list of individual terms.

**Comment by poojarao8** [comment] 2023-10-25 17:15
Okay, got it - thanks! It might be good to add that it's unordered in the Python docs.

**Comment by bettinaheim** [comment] 2023-11-06 18:38
I'll close this as by design for performance reasons. @poojarao8 What we could reasonably do is to allow you to output the spin_op following a particular sorting, in which case we would sort the terms before printing. Please feel free to reopen this with a concrete request for what kind of ordering should be supported (order in the code is not an option - it would have to be something like like order by index/alphabet).

**Closed by bettinaheim** 2023-11-06 18:38 UTC
