### ISSUE TITLE
Expectation values on observe_n 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#230] opened 2023-06-06 14:26 UTC
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

For `observe` we can do this: 

```
exp_vals = [cudaq.observe(kernel, h, x[i], params).expectation_z() for i in range(x.shape[0])]
```

`observe_n` removes the for loop but then adds another one to retrieve expectation values: 

```
  exp_vals_list = cudaq.observe_n(kernel, h, x, params)
  
  exp_vals = [i.expectation_z() for i in exp_vals_list]

```

Can we do something like: 

```
  exp_vals = cudaq.observe_n(kernel, h, x, params).expectation_z()

```

**Comment by amccaskey** [comment] 2023-06-06 14:36
I would say no since there may be more data associated with each invocation than just the expected value (e.g. the raw counts).

**Comment by bettinaheim** [comment] 2023-10-26 10:41
Closing as by design.

**Closed by bettinaheim** 2023-10-26 10:41 UTC
Labels: enhancement, wontfix
