### ISSUE TITLE
cuda-quantum docker cpu have different result with gpu

### ISSUE THREAD

**Issue by Guogggg** [NVIDIA/cuda-quantum#583] opened 2023-08-29 06:19 UTC
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

`import os
import numpy as np

import cudaq
from cudaq import chemistry
geometry = [('Li', (0., 0., 0.)), ('H', (0., 0., 1.5))]
molecule, data = chemistry.create_molecular_hamiltonian(
    geometry, 'sto-3g', 1, 0)
cudaq.set_target('nvidia')
numElectrons = data.n_electrons
numQubits = 2 * data.n_orbitals

kernel, thetas = cudaq.make_kernel(list)
qubits = kernel.qalloc(12)

kernel.x(qubits[0])
kernel.x(qubits[1])
kernel.x(qubits[2])
kernel.x(qubits[3])

cudaq.kernels.uccsd(kernel, qubits, thetas, numElectrons, numQubits)

num_parameters = cudaq.kernels.uccsd_num_parameters(numElectrons, numQubits)
print("num_parameters: ", num_parameters)
optimizer = cudaq.optimizers.SPSA()
energy, params = cudaq.vqe(kernel,
                            molecule,
                            optimizer,
                            parameter_count=num_parameters)
print(energy, params)

`
When I comment out cudaq.set_target('nvidia'), the result is:
`<H> = -4.703793
<H> = -4.758690
<H> = -7.863358
<H> = -4.931899
<H> = -4.906214
<H> = -7.863358
-7.863357621533178 [-1.17716665170367e-12, -1.17716665170367e-12, 1.17716665170367e-12, 1.17716665170367e-12, -3.5484976526133087e-12, -1.17716665170367e-12, 3.5484976526133087e-12, 3.5484976526133087e-12, 3.5484976526133087e-12, -3.5484976526133087e-12, -3.5484976526133087e-12, -1.17716665170367e-12, -1.17716665170367e-12, 1.17716665170367e-12, 1.17716665170367e-12, 1.17716665170367e-12, 3.5484976526133087e-12, 1.17716665170367e-12, -1.17716665170367e-12, 1.17716665170367e-12, -1.17716665170367e-12, 3.5484976526133087e-12, 3.5484976526133087e-12, -3.5484976526133087e-12, -1.17716665170367e-12, -1.17716665170367e-12, 3.5484976526133087e-12, 1.17716665170367e-12, -1.17716665170367e-12, -3.5484976526133087e-12, 3.5484976526133087e-12, -1.17716665170367e-12, -3.5484976526133087e-12, 1.17716665170367e-12, -3.5484976526133087e-12, 1.17716665170367e-12, 3.5484976526133087e-12, 1.17716665170367e-12, -1.17716665170367e-12, -3.5484976526133087e-12, 3.5484976526133087e-12, -3.5484976526133087e-12, -3.5484976526133087e-12, -1.17716665170367e-12, 3.5484976526133087e-12, 1.17716665170367e-12, 3.5484976526133087e-12, -1.17716665170367e-12, -3.5484976526133087e-12, -1.17716665170367e-12, 3.5484976526133087e-12, 1.17716665170367e-12, -1.17716665170367e-12, 1.17716665170367e-12, -3.5484976526133087e-12, -1.17716665170367e-12, -1.17716665170367e-12, -3.5484976526133087e-12, -3.5484976526133087e-12, -3.5484976526133087e-12, -1.17716665170367e-12, 1.17716665170367e-12, 3.5484976526133087e-12, 1.17716665170367e-12, 1.17716665170367e-12, -1.17716665170367e-12, -1.17716665170367e-12, -3.5484976526133087e-12, 3.5484976526133087e-12, -3.5484976526133087e-12, -3.5484976526133087e-12, 3.5484976526133087e-12, -1.17716665170367e-12, -1.17716665170367e-12, 3.5484976526133087e-12, -1.17716665170367e-12, 1.17716665170367e-12, 1.17716665170367e-12, -3.5484976526133087e-12, -3.5484976526133087e-12, 3.5484976526133087e-12, -1.17716665170367e-12, 3.5484976526133087e-12, -3.5484976526133087e-12, 3.5484976526133087e-12, -1.17716665170367e-12, 3.5484976526133087e-12, 1.17716665170367e-12, 1.17716665170367e-12, -1.17716665170367e-12, 1.17716665170367e-12, -1.17716665170367e-12]
`

but,When I uncomment out cudaq.set_target('nvidia'), the result is:
`
<H> = -4.103592
<H> = -4.103592
<H> = -4.103592
<H> = -4.103592
<H> = -4.103592
<H> = -4.103592
-4.10359188271741 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

`

### Steps to reproduce the bug

Download the cuda-quantum docker according to the documentation, then run the above code to reproduce the result via set_target('nvidia')

### Expected behavior

The gpu should run faster, and the result should be the same

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 0.4.0
- **Python version**: Python 3.10.6
- **C++ compiler**: 11.30
- **Operating system**:  ubuntu 22.04

**Comment by bmhowe23** [comment] 2023-08-29 13:54
What GPU are you using? I tried to reproduce the problem on both an A100 and A6000 and I was unable to reproduce the different behavior when toggling whether or not the nvidia target was being used.

**Comment by Guogggg** [comment] 2023-08-30 01:07
> 您使用什么 GPU？我尝试在 A100 和 A6000 上重现该问题，但在切换是否使用 nvidia 目标时无法重现不同的行为。

I am using Tesla T4 and A100 GPUs with CUDA version 12.2 and nvcc version 12.2. When I use the CPU to calculate the energy of LiH, the computed result is very close to the accurate value. However, when I use the GPU, the computed result differs significantly.

**Comment by Guogggg** [comment] 2023-08-30 02:47
> 您使用什么GPU？我尝试在A100和A6000上恢复该问题，但在切换是否使用nvidia目标时无法恢复不同的行为。
this is demo_code
![image](https://github.com/NVIDIA/cuda-quantum/assets/68990588/4cae19a7-1dbd-4677-a902-8c57076ab736)
and this is cpu result
![image](https://github.com/NVIDIA/cuda-quantum/assets/68990588/38399467-4052-479a-b7c3-947db6b1a29a)

after, When I add set_target('nvidia')
gpu result:
![image](https://github.com/NVIDIA/cuda-quantum/assets/68990588/2f57fe00-5097-4f9d-9e2c-36c47dfddc21)

**Comment by 1tnguyen** [comment] 2023-08-30 06:30
Hi @Guogggg,

I cannot reproduce the bug on my system with A100 GPU.

My steps:

- Docker:

```
docker run --gpus all -it --rm nvcr.io/nvidia/cuda-quantum:0.4.0
```

- Run the above example (`nvidia` target):

```
 python3 -m pip install openfermionpyscf
 python3 test.py
```

- Result:
```
cudaq@9f453424dea0:~$ python3 test.py
/home/cudaq/.local/lib/python3.10/site-packages/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, the same to the B3LYP functional in Gaussian and ORCA (issue 1480). To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
num_parameters:  92
<H> = -4.703681
<H> = -4.758564
<H> = -7.862600
<H> = -4.931717
<H> = -4.906044
<H> = -7.862600
-7.862599938916624 [-1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 3.5473221193526153e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, 1.1771209396372758e-12, -3.5473221193526153e-12, 1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, -1.1771209396372758e-12]
```

**Comment by Guogggg** [comment] 2023-08-30 06:43
> 你好@Guogggg,
> 
> 我无法在使用 A100 GPU 的系统上重现该错误。
> 
> 我的步骤：
> 
> * 码头工人：
> 
> ```
> docker run --gpus all -it --rm nvcr.io/nvidia/cuda-quantum:0.4.0
> ```
> 
> * 运行上面的例子（`nvidia`目标）：
> 
> ```
>  python3 -m pip install openfermionpyscf
>  python3 test.py
> ```
> 
> * 结果：
> 
> ```
> cudaq@9f453424dea0:~$ python3 test.py
> /home/cudaq/.local/lib/python3.10/site-packages/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, the same to the B3LYP functional in Gaussian and ORCA (issue 1480). To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
>   warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
> num_parameters:  92
> <H> = -4.703681
> <H> = -4.758564
> <H> = -7.862600
> <H> = -4.931717
> <H> = -4.906044
> <H> = -7.862600
> -7.862599938916624 [-1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 3.5473221193526153e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, 1.1771209396372758e-12, -3.5473221193526153e-12, 1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, -3.5473221193526153e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, -3.5473221193526153e-12, 3.5473221193526153e-12, -1.1771209396372758e-12, 3.5473221193526153e-12, 1.1771209396372758e-12, 1.1771209396372758e-12, -1.1771209396372758e-12, 1.1771209396372758e-12, -1.1771209396372758e-12]
> ```
What version of cuda and nvcc are you using?

Need to download custatevec using pip?

**Comment by bmhowe23** [comment] 2023-08-30 14:17
Like @1tnguyen, I didn't need to install custatevec in order to run this test. Also, nvcc is not installed in the docker container image because it is not needed unless you are modifying cuda-quantum source code, but nvidia-smi (which is installed in the container and uses the underlying driver on the host system) reports that it is using CUDA version 12.2 on one of my systems and 12.0 on the other.

**Comment by Guogggg** [comment] 2023-08-31 01:51
> Like @1tnguyen, I didn't need to install custatevec in order to run this test. Also, nvcc is not installed in the docker container image because it is not needed unless you are modifying cuda-quantum source code, but nvidia-smi (which is installed in the container and uses the underlying driver on the host system) reports that it is using CUDA version 12.2 on one of my systems and 12.0 on the other.

docker:
docker run --gpus all -it -u root --rm nvcr.io/nvidia/cuda-quantum:0.4.0

cd /home/cudaq/examples/python

For any example, as long as I add cudaq.set_target("nvidia"),
the calculation results are incorrect.

**Comment by schweitzpgi** [comment] 2023-10-19 21:54
Claims to be fixed.

**Comment by 1tnguyen** [comment] 2023-10-20 00:26
@Guogggg We were able to reproduce this issue with V100 GPUs and fixed it in https://github.com/NVIDIA/cuda-quantum/pull/696. 

I'm closing this issue now but please feel free to file another if it doesn't work for you. 
Thanks for reporting the issue.

**Closed by 1tnguyen** 2023-10-20 00:26 UTC
Labels: verify and close
