### ISSUE TITLE
find_package(CUDAQ) disables CMAKE_EXPORT_COMPILE_COMMANDS

### ISSUE THREAD

**Issue by orclassiq** [NVIDIA/cuda-quantum#382] opened 2023-07-09 11:54 UTC
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When adding the `find_package(CUDAQ REQUIRED)` line to the `CMakeLists.txt` file and passing the `-DCMAKE_EXPORT_COMPILE_COMMANDS=1` to CMake, the `compile_commands.json` file isn't created.

This file is used by tools such as `clangd` and `clang-tidy`. 

### Steps to reproduce the bug

Create the following `CMakeLists.txt` file:
```cmake
cmake_minimum_required(VERSION 3.24 FATAL_ERROR)
project(myCudaQApp LANGUAGES CXX)
find_package(CUDAQ REQUIRED)
add_executable(test_app main.cpp)
```
And the following `main.cpp` file:
```c++
int main() {
}
```

Then run the following script:
```shell
mkdir -p build
cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```

The `build` directory doesn't contain a `compile_commands.json` file.

### Expected behavior

When running the script, a `compile_commands.json` file should be created.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **`cuda-quantum` docker image version**: sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d. Download using docker pull ghcr.io/nvidia/cuda-quantum@sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d
- **CMake version** - 3.26.4, installed via `pip install cmake`.

**Comment by 1tnguyen** [comment] 2023-08-11 14:26
I dug into this a while back, and it looks like this is a limitation of CMake itself. In particular, CMake hardcoded the list of source languages that it will support compile command export, e.g., for `Makefile` generator:
https://gitlab.kitware.com/cmake/cmake/-/blob/master/Source/cmMakefileTargetGenerator.cxx#L966-974

The `lang_can_export_cmds` bool, if `false`, will bypass the `compile_commands.json` export. Since we define a new CMake `<LANG>` (CUDAQ), the `lang_can_export_cmds` will thus be `false`. By the look of it, it'd be difficult to modify this behavior since the condition is rigid.

**Comment by bettinaheim** [comment] 2023-10-26 09:57
Closing this a "by design (of CMake)". Please feel free to reopen if there is a workaround that seems reasonable for this.

**Closed by bettinaheim** 2023-10-26 09:57 UTC
Labels: needs triage
